### ISSUE TITLE
Backend : API/UML Diagram

### ISSUE THREAD

**Issue by a2jensen** [a2jensen/CSE-110-TritonMates#4]

**Comment by ahmedCoder12424** [comment]
Hours: 6 hours
Description: An API/UML diagram illustrates the architecture and interactions of an application programming interface (API) using Unified Modeling Language (UML) notation. It shows the components, endpoints, data flow, and relationships, helping developers understand how to integrate and use the API effectively.

**Comment by ahmedCoder12424** [comment]
complete
https://www.figma.com/design/P2EPILwfhU7WlJFAczb6Np/API-UML-Diagram?node-id=0-1&node-type=canvas&t=62fRdevY9tcoqU1x-0
