### ISSUE TITLE
Add Jest Tests for Tasks

### ISSUE THREAD

**Issue by ahmedCoder12424** [a2jensen/CSE-110-TritonMates#50]

**Comment by allen-vu** [comment]
renamed title from events page to tasks component for jest testing due to direct work prior

**Comment by allen-vu** [comment]
update before demo: rendering complications once the backend was implemented but renders did work when the frontend was strictly done. There was a sanity test that checked if a text was present but now the routing or external dependencies has been difficult to debug between the framework and jest
